# Generated by Django 4.2.8 on 2025-12-27 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_paymentmethod_purchase_refund_promocode_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/media/%Y/%m/')),
                ('original_filename', models.CharField(help_text='Оригинальное имя файла', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Название для отображения', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Описание файла')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('audio', 'Аудио'), ('other', 'Другое')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Размер файла в байтах')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='courses.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медиа-файл курса',
                'verbose_name_plural': 'Медиа-файлы курсов',
                'ordering': ['-created_at'],
            },
        ),
    ]
