# Generated by Django 4.2.8 on 2025-12-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('graded', 'Оценено'), ('returned', 'Возвращено на доработку')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Видео'), ('article', 'Статья'), ('quiz', 'Тест'), ('assignment', 'Задание')], default='video', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Объяснение, показываемое после ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Баллы за правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple', 'Множественный выбор'), ('single', 'Одиночный выбор'), ('true_false', 'Правда/Ложь'), ('text', 'Текстовый ответ')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts_limit',
            field=models.PositiveIntegerField(default=3, help_text='Максимальное количество попыток'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Минимальный % для прохождения'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='show_answers',
            field=models.BooleanField(default=True, help_text='Показывать правильные ответы после завершения'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Лимит времени на тест в минутах', null=True),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('text', 'Текст/Теория'), ('video', 'Видео'), ('quiz_single', 'Тест: один ответ'), ('quiz_multiple', 'Тест: несколько ответов'), ('quiz_sorting', 'Сортировка'), ('quiz_matching', 'Сопоставление'), ('fill_blanks', 'Заполнить пропуски'), ('numeric', 'Числовой ответ'), ('text_answer', 'Текстовый ответ'), ('free_answer', 'Свободный ответ (эссе)'), ('code', 'Программирование'), ('sql', 'SQL задача')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, help_text='Название шага (опционально)', max_length=200)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('points', models.PositiveIntegerField(default=1, help_text='Баллы за правильный ответ')),
                ('is_required', models.BooleanField(default=True, help_text='Обязательный для прохождения урока')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('failed', 'Не пройден')], default='not_started', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('answer_data', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Баллы', max_digits=5, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, help_text='Автоматический или ручной отзыв')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='courses.enrollment')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.step')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
                'ordering': ['step__order'],
                'unique_together': {('enrollment', 'step')},
            },
        ),
    ]
