# Generated by Django 4.2.8 on 2025-12-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_step_and_stepprogress_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
    ]
